### ISSUE TITLE
Need Wiki Guide

### ISSUE THREAD

**Issue by GoliathDeveloper** [Phatye/chartjs.mvc#2]
Please write a wiki guide as i am having trouble adding data

**Comment by Phatye** [comment]
Will​ do that ASAP.

Best regards.
Fatai Salami.

**Comment by Phatye** [comment]
Please check the Readme and let me know if that is okay

**Comment by GoliathDeveloper** [comment]
using your example 

Compiler Error Message: CS1973: 'HtmlHelper<dynamic>' has no applicable method named 'CreateChartJs' but appears to have an extension method by that name. Extension methods cannot be dynamically dispatched. Consider casting the dynamic arguments or calling the extension method without the extension method syntax.

**Comment by GoliathDeveloper** [comment]
could you add a example for each type e.g. pie, dougnut and line and is there an easy way of getting a model with data into the dataset with dynamic data?

**Comment by Phatye** [comment]
I will work on the examples over the weekend.
I don't understand the second part. Can you explain?

**Comment by GoliathDeveloper** [comment]
i have modified the following 

    public class DataProperty
    {
        public List<string> Labels { get; set; }

    public class DataSet
    {
        public List<double> Data { get; set; }

and am looking to make some more minor adjustments to the code like adding enums

**Comment by GoliathDeveloper** [comment]
Hi below is my example code 

private TestModel db = new TestModel();

public ActionResult _PieTest()
        {
            List<Score> PScores = db.Scores.ToList();
            List<SimpleData> lData = ScoresByCat(PScores);
            //Create List of Values
            List<double> dList = new List<double>();
            //Create List of Labels
            List<string> sList = new List<string>();
            //Create List of Colors
            List<string> sColorList = new List<string>();
            //Cycle Through Values and Add to Lists
            foreach (SimpleData sData in lData)
            {
                dList.Add(sData.Value);
                sList.Add(sData.Label);
                sColorList.Add(ChartJs.Mvc.Extensions.ColorConverter.GetHexValue(sData.ColorRaw));
            }
            var dSet = new DataSet
            {
                Type = ChartJs.Mvc.Chart.ChartType.pie.ToString(),
                Data = dList,
                BackgroundColor = sColorList,
                Fill = true,
                Label = "Test"
            };
            //create an instance of the chart
            var chart = new ChartJs.Mvc.Chart
            {
                //accepts a list of datasets. A dataset represents a chart to be plotted on the canvas
                Data = new DataProperty
                {
                    Datasets = new List<DataSet> { dSet },
                    Labels = sList
                },
                Type = ChartJs.Mvc.Chart.ChartType.pie.ToString(),
                //option property for the chart
                //Options = option;
            };
            //pass the chart to the view
            ViewBag.Test = chart;
            return View("_PieTest");
			}


@using ChartJs.Mvc.Extensions;
@using ChartJs.Mvc.Data;
@using ChartJs.Mvc.Options;
@{
    ChartJs.Mvc.SimpleChart TestChart = ViewBag.Test;
    TestChart.Type = ChartJs.Mvc.SimpleChart.ChartType.doughnut.ToString();
}
<script src="~/Scripts/Chart.js"></script>
<div class="panel panel-default">

    <canvas class="text-center" id="TestChart" height="100" width="100"></canvas>
    @Html.CreateChartJs("TestChart", TestChart)
</div>

using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ChartJs.Mvc.Data
{
    public class SimpleData
    {
        /// <summary>
        /// Gets or sets the value.
        /// </summary>
        public double Value
        {
            get;
            set;
        }

        /// <summary>
        /// Gets or sets the color.
        /// </summary>
        public string Color
        {
            get;
            set;
        }
        public Color ColorRaw
        {
            get;
            set;
        }
        /// <summary>
        /// Gets or sets the highlight.
        /// </summary>
        public string Highlight
        {
            get;
            set;
        }

        /// <summary>
        /// Gets or sets the label.
        /// </summary>
        public string Label
        {
            get;
            set;
        }
    }
}

**Comment by GoliathDeveloper** [comment]
i will review the code tomorrow and see if i can simplify it

**Comment by GoliathDeveloper** [comment]
i have modified the DataSet Class adding additional options (See Below)

namespace ChartJs.Mvc.Data
{
    public class DataSet
    {
        public enum PointStyleType { triangle,rect, rectRounded,rectRot,cross,crossRot,star,line,dash }
        public List<double> Data { get; set; }
        public string Label { get; set; }
        public bool? Fill { get; set; }
        public dynamic BackgroundColor { get; set; }
        public int BorderWidth { get; set; }
        public string BorderColor { get; set; }
        public dynamic PointBackgroundColor { get; set; }
        public string PointBorderColor { get; set; }
        public string PointStyle { get; set; }
        public int PointRadius { get; set; }
        public string Type { get; set; }   
        public string YAxisID { get; set; }
    }
}
